"""add properties table

Revision ID: 7064f49ca872
Revises: abd9dfc16840
Create Date: 2026-04-11 15:01:11.294403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7064f49ca872'
down_revision: Union[str, None] = 'abd9dfc16840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('municipality', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=9), nullable=False),
    sa.Column('total_area_ha', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('own_area_ha', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('leased_area_ha', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('protected_area_ha', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('crop_area_ha', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_user_id'), 'properties', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_user_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
